<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110714195621 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE fos_comment_thread (identifier VARCHAR(255) NOT NULL, permalink VARCHAR(255) NOT NULL, isCommentable TINYINT(1) NOT NULL, numComments INT NOT NULL, lastCommentAt DATETIME DEFAULT NULL, PRIMARY KEY(identifier)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE test_comment (id INT AUTO_INCREMENT NOT NULL, thread_identifier VARCHAR(255) DEFAULT NULL, body VARCHAR(255) NOT NULL, ancestors VARCHAR(1024) DEFAULT NULL, depth INT NOT NULL, createdAt DATETIME NOT NULL, INDEX IDX_483586A4B57616E2 (thread_identifier), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE test_notification (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, message VARCHAR(255) NOT NULL, readAt DATETIME DEFAULT NULL, createdAt DATETIME NOT NULL, INDEX IDX_93D296FAA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE app_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, algorithm VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_88BDF3E992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_88BDF3E9A0D96FBF (email_canonical), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE test_comment ADD FOREIGN KEY (thread_identifier) REFERENCES fos_comment_thread(identifier)");
        $this->addSql("ALTER TABLE test_notification ADD FOREIGN KEY (user_id) REFERENCES app_user(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE test_comment DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE test_notification DROP FOREIGN KEY ");
        $this->addSql("DROP TABLE fos_comment_thread");
        $this->addSql("DROP TABLE test_comment");
        $this->addSql("DROP TABLE test_notification");
        $this->addSql("DROP TABLE app_user");
    }
}
